// File: lib/demo-data.ts
/** In-memory demo dataset — used when MongoDB is unavailable */
export const DEMO_STYLES = [
  {
    _id: 'demo-001',
    designNumber: 'DN-2026-0142',
    buyerName: 'H&M Europe',
    buyer: { name: 'H&M Europe', email: 'buying@hm-demo.com', role: 'buyer' },
    merchant: { name: 'Rahul Sharma', email: 'rahul@factory.com', role: 'merchant' },
    sampleType: 'fit',
    fabricDetails: { type: 'Cotton Twill', description: 'Stretch twill for chinos', gsm: 280, color: 'Navy' },
    rawMaterials: { buttonsPerGarment: 1, other: 'YKK zip, main label' },
    status: 'sampling',
    priority: 'medium',
    sampleDeadline: daysFromNow(5),
    deliveryDate: daysFromNow(120),
    quantity: 800,
    comments: [
      { user: 'Rahul Sharma', text: 'Buyer wants fit sample this week. Delivery is Q3 — lower shipment urgency.', timestamp: daysFromNow(-2) },
      { user: 'Cutting Dept', text: 'Pattern under development. Cutting team aligned for next Monday.', timestamp: daysFromNow(-1) },
    ],
    createdAt: daysFromNow(-10),
    updatedAt: daysFromNow(-1),
  },
  {
    _id: 'demo-002',
    designNumber: 'DN-2026-0089',
    buyerName: 'Zara Home',
    buyer: { name: 'Zara Home', email: 'merch@zarahome-demo.com', role: 'buyer' },
    merchant: { name: 'Priya Mehta', email: 'priya@factory.com', role: 'merchant' },
    sampleType: 'proto',
    fabricDetails: { type: 'Linen Blend', description: 'Washed linen for shirts', gsm: 160, color: 'Ecru' },
    rawMaterials: { buttonsPerGarment: 7 },
    status: 'production',
    priority: 'urgent',
    sampleDeadline: daysFromNow(-5),
    deliveryDate: daysFromNow(28),
    quantity: 5200,
    comments: [
      { user: 'Priya Mehta', text: 'Delivery next month! Fabric chased — pattern must close in 15 days.', timestamp: daysFromNow(-3) },
      { user: 'Supervisor', text: 'PRIORITY: Shipment beats fit-sample rush on DN-0142. Pull capacity here.', timestamp: daysFromNow(-2) },
    ],
    createdAt: daysFromNow(-25),
    updatedAt: daysFromNow(0),
  },
  {
    _id: 'demo-003',
    designNumber: 'DN-2026-0201',
    buyerName: 'Mango',
    buyer: { name: 'Mango', email: 'tech@mango-demo.com', role: 'buyer' },
    merchant: { name: 'Amit Kumar', email: 'amit@factory.com', role: 'merchant' },
    sampleType: 'fit',
    fabricDetails: { type: 'Poly Viscose', description: 'Printed blouse fabric', gsm: 120, color: 'Floral Print' },
    rawMaterials: { buttonsPerGarment: 8, other: 'Shell buttons PG-12' },
    status: 'approved',
    priority: 'high',
    sampleDeadline: daysFromNow(12),
    deliveryDate: daysFromNow(45),
    quantity: 3200,
    comments: [
      { user: 'Amit Kumar', text: 'Fit sample approved. Moving to cutting — reverse plan from 45-day delivery.', timestamp: daysFromNow(-1) },
    ],
    createdAt: daysFromNow(-18),
    updatedAt: daysFromNow(-1),
  },
  {
    _id: 'demo-004',
    designNumber: 'DN-2026-0055',
    buyerName: 'Target USA',
    buyer: { name: 'Target USA', email: 'sourcing@target-demo.com', role: 'buyer' },
    merchant: { name: 'Rahul Sharma', email: 'rahul@factory.com', role: 'merchant' },
    sampleType: 'production',
    fabricDetails: { type: 'Fleece', description: 'Brushed fleece hoodie', gsm: 320, color: 'Heather Grey' },
    rawMaterials: { buttonsPerGarment: 0, other: 'Drawcord, kangaroo pocket trim' },
    status: 'pending',
    priority: 'high',
    sampleDeadline: daysFromNow(18),
    deliveryDate: daysFromNow(55),
    quantity: 12000,
    comments: [],
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-3),
  },
  {
    _id: 'demo-005',
    designNumber: 'DN-2026-0118',
    buyerName: 'Uniqlo',
    buyer: { name: 'Uniqlo', email: 'dev@uniqlo-demo.com', role: 'buyer' },
    merchant: { name: 'Sneha Patel', email: 'sneha@factory.com', role: 'merchant' },
    sampleType: 'proto',
    fabricDetails: { type: 'Jersey Knit', description: 'Single jersey T-shirt', gsm: 180, color: 'White' },
    rawMaterials: { buttonsPerGarment: 0 },
    status: 'sampling',
    priority: 'medium',
    sampleDeadline: daysFromNow(10),
    deliveryDate: daysFromNow(75),
    quantity: 450,
    comments: [
      { user: 'Sneha Patel', text: 'Small qty — can slot between bulk runs if cutting free.', timestamp: daysFromNow(-2) },
    ],
    createdAt: daysFromNow(-7),
    updatedAt: daysFromNow(-2),
  },
  {
    _id: 'demo-006',
    designNumber: 'DN-2026-0300',
    buyerName: 'Gap Inc',
    buyer: { name: 'Gap Inc', email: 'pd@gap-demo.com', role: 'buyer' },
    merchant: { name: 'Priya Mehta', email: 'priya@factory.com', role: 'merchant' },
    sampleType: 'fit',
    fabricDetails: { type: 'Denim', description: 'Stretch denim 3/1 twill', gsm: 340, color: 'Indigo' },
    rawMaterials: { buttonsPerGarment: 5, other: 'Rivets, leather patch' },
    status: 'completed',
    priority: 'low',
    sampleDeadline: daysFromNow(-30),
    deliveryDate: daysFromNow(-2),
    quantity: 2800,
    comments: [
      { user: 'Priya Mehta', text: 'Ex-factory completed. Shipment docs sent to buyer platform.', timestamp: daysFromNow(-5) },
    ],
    createdAt: daysFromNow(-90),
    updatedAt: daysFromNow(-2),
  },
];

export const DEMO_MERCHANTS = [
  { name: 'Rahul Sharma', styles: 2, buyers: 2 },
  { name: 'Priya Mehta', styles: 2, buyers: 2 },
  { name: 'Amit Kumar', styles: 1, buyers: 1 },
  { name: 'Sneha Patel', styles: 1, buyers: 1 },
];

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}